apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-haproxy-config
data:
  haproxy.cfg: |
    global
      log stdout format raw local0
      maxconn 2048

    defaults
      log     global
      mode    http
      option  httplog
      timeout connect 10s
      timeout client  1m
      timeout server  1m

    frontend http_front
      bind *:80
      default_backend zabbix_web_back

    backend zabbix_web_back
      balance roundrobin
      server zabbix-web-1 zabbix-web:80 check

    frontend zbx_trapper_front
      bind *:10051
      mode tcp
      default_backend zabbix_server_back

    backend zabbix_server_back
      mode tcp
      balance roundrobin
      server zabbix-server-1 zabbix-server:10051 check
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-ha
spec:
  type: LoadBalancer
  selector:
    app: zabbix-haproxy
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: zbx-trapper
      port: 10051
      targetPort: 10051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-haproxy
  template:
    metadata:
      labels:
        app: zabbix-haproxy
    spec:
      containers:
        - name: haproxy
          image: haproxy:2.9
          ports:
            - containerPort: 80
            - containerPort: 10051
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
      volumes:
        - name: haproxy-config
          configMap:
            name: zabbix-haproxy-config
