---
mysql_image: "mysql:8.0"
mysql_replicas: 1
mysql_storage_size: "10Gi"
mysql_service_port: 3306
mysql_haproxy_port: 3307

db_root_password: "ChangeMeRoot!"
db_zabbix_password: "ChangeMeZabbix!"
db_user: "zabbix"
db_name: "zabbix"
