kubeconfig_path: "{{ lookup('env', 'KUBECONFIG') | default('~/.kube/config', true) }}"
kube_context: ""
zabbix_namespace: "zabbix-prod"

db_root_password: "ProdRootPassREPLACE!"
db_zabbix_password: "ProdZabbixPassREPLACE!"
db_user: "zabbix"
db_name: "zabbix"

zabbix_server_image: "zabbix/zabbix-server-mysql:alpine-7.4-latest"
zabbix_web_image: "zabbix/zabbix-web-nginx-mysql:alpine-7.4-latest"
mysql_image: "mysql:8.0"
haproxy_image: "haproxy:2.9"

mysql_replicas: 2
mysql_storage_size: "50Gi"
mysql_service_port: 3306
mysql_haproxy_port: 3307

zabbix_server_replicas: 3
zabbix_web_replicas: 3

grafana_image: "grafana/grafana:10.4.0"
grafana_admin_user: "admin"
grafana_admin_password: "ProdGrafanaPassREPLACE!"
grafana_service_type: "LoadBalancer"
